# Generated by Django 5.2.6 on 2025-09-26 20:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=20
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Tell us about yourself and your farming experience",
                        max_length=500,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("batken_city", "Batken City"),
                            ("kyzyl_kiya", "Kyzyl-Kiya"),
                            ("sulukta", "Sulukta"),
                            ("kadamjay", "Kadamjay"),
                            ("leylek", "Leylek"),
                            ("batken_villages", "Batken Villages"),
                            ("other", "Other Region"),
                        ],
                        default="batken_city",
                        max_length=50,
                    ),
                ),
                (
                    "village_or_address",
                    models.CharField(
                        blank=True,
                        help_text="Village name or street address",
                        max_length=200,
                    ),
                ),
                (
                    "farmer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Farmer"),
                            ("cooperative", "Agricultural Cooperative"),
                            ("company", "Agricultural Company"),
                            ("expert", "Agricultural Expert/Consultant"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "farm_size",
                    models.CharField(
                        choices=[
                            ("small", "Small (< 5 hectares)"),
                            ("medium", "Medium (5-50 hectares)"),
                            ("large", "Large (> 50 hectares)"),
                            ("none", "No farm (Expert/Consultant)"),
                        ],
                        default="small",
                        max_length=20,
                    ),
                ),
                (
                    "main_crops",
                    models.CharField(
                        blank=True,
                        help_text="Main crops you grow (comma separated)",
                        max_length=300,
                    ),
                ),
                (
                    "farming_experience",
                    models.PositiveIntegerField(
                        default=0, help_text="Years of farming experience"
                    ),
                ),
                (
                    "is_verified_farmer",
                    models.BooleanField(
                        default=False, help_text="Verified by agricultural experts"
                    ),
                ),
                (
                    "reputation_score",
                    models.IntegerField(
                        default=0, help_text="Community reputation score"
                    ),
                ),
                ("receive_notifications", models.BooleanField(default=True)),
                ("receive_market_alerts", models.BooleanField(default=True)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("ky", "Kyrgyz"),
                            ("ru", "Russian"),
                            ("en", "English"),
                        ],
                        default="ky",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_activity",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FarmerConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("follower", "following")},
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("post_created", "Blog Post Created"),
                            ("comment_added", "Comment Added"),
                            ("crop_viewed", "Crop Information Viewed"),
                            ("market_checked", "Market Prices Checked"),
                            ("soil_test", "Soil Test Completed"),
                            ("pest_lookup", "Pest/Disease Lookup"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="users_usera_user_id_f30086_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-timestamp"],
                        name="users_usera_activit_5e7a89_idx",
                    ),
                ],
            },
        ),
    ]
