# Generated by Django 5.2.6 on 2025-09-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="farm_size",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="main_crops",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="farmer_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual Farmer"),
                    ("cooperative", "Agricultural Cooperative"),
                    ("commercial", "Commercial Farm Enterprise"),
                    ("expert", "Agricultural Expert/Consultant"),
                ],
                default="individual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="farming_experience",
            field=models.CharField(
                choices=[
                    ("0-1", "0-1 years (Beginner)"),
                    ("1-3", "1-3 years (Novice)"),
                    ("3-9", "3-9 years (Intermediate)"),
                    ("9-15", "9-15 years (Experienced)"),
                    ("15+", "15+ years (Expert)"),
                ],
                default="0-1",
                help_text="Years of farming experience",
                max_length=10,
            ),
        ),
    ]
