# Generated by Django 5.2.6 on 2025-09-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_update_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_choice",
            field=models.CharField(
                choices=[
                    ("farmer_man_1", "👨\u200d🌾 Male Farmer 1"),
                    ("farmer_man_2", "🧑\u200d🌾 Male Farmer 2"),
                    ("farmer_woman_1", "👩\u200d🌾 Female Farmer 1"),
                    ("farmer_woman_2", "🧕\u200d🌾 Female Farmer 2"),
                    ("default", "👤 Default Avatar"),
                ],
                default="default",
                help_text="Choose a farmer avatar",
                max_length=20,
            ),
        ),
    ]
