# Generated by Django 5.2.6 on 2025-09-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_avatar_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar_choice",
            field=models.CharField(
                choices=[
                    ("farmer_man_1", "👨\u200d🌾 Male Farmer 1"),
                    ("farmer_man_2", "🧑\u200d🌾 Male Farmer 2"),
                    ("farmer_woman_1", "👩\u200d🌾 Female Farmer 1"),
                    ("farmer_woman_2", "🧕 Female Farmer 2"),
                    ("default", "👤 Default"),
                ],
                default="default",
                help_text="Choose a farmer avatar",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                help_text="Contact phone number for other farmers to reach you",
                max_length=20,
            ),
        ),
    ]
