# Generated by Django 5.2.6 on 2025-09-30 12:00

from django.db import migrations


def add_placeholder_phone_numbers(apps, schema_editor):
    """Add placeholder phone numbers for existing users without phone numbers"""
    UserProfile = apps.get_model('users', 'UserProfile')
    
    # Update users with empty phone numbers
    profiles_to_update = UserProfile.objects.filter(phone_number='')
    for profile in profiles_to_update:
        # Use a placeholder that indicates they need to update their phone
        profile.phone_number = 'UPDATE_REQUIRED'
        profile.save()


def reverse_add_placeholder_phone_numbers(apps, schema_editor):
    """Reverse the migration by clearing placeholder phone numbers"""
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.filter(phone_number='UPDATE_REQUIRED').update(phone_number='')


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_userprofile_avatar_choice_and_more"),
    ]

    operations = [
        migrations.RunPython(
            add_placeholder_phone_numbers,
            reverse_add_placeholder_phone_numbers,
        ),
    ]
