# Generated by Django 5.2.6 on 2025-09-30 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("users", "0005_auto_20250930_1200"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="region",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.city",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.country",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="region_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="locations.region",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="region_old",
            field=models.CharField(
                blank=True,
                help_text="Old region field - will be removed",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="village_or_address",
            field=models.CharField(
                blank=True,
                help_text="Specific address, village name, or additional location details",
                max_length=200,
            ),
        ),
    ]
