# Generated by Django 5.2.7 on 2025-10-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_userprofile_region_userprofile_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp number for easy communication (optional)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar_choice",
            field=models.CharField(
                choices=[
                    ("farmer_man_1", "👨\u200d🌾"),
                    ("farmer_woman_1", "👩\u200d🌾"),
                    ("default", "👤"),
                ],
                default="default",
                help_text="Choose a farmer avatar",
                max_length=20,
            ),
        ),
    ]
