# Generated by Django 5.2.7 on 2025-10-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userprofile_whatsapp_number_and_more"),
    ]

    operations = []
