# Generated by Django 5.2.7 on 2025-10-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20251006_0844"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar_choice",
            field=models.CharField(
                choices=[
                    ("farmer_man_1", "👨\u200d🌾"),
                    ("farmer_woman_1", "👩\u200d🌾"),
                    ("default", "User Icon"),
                ],
                default="default",
                help_text="Choose a farmer avatar",
                max_length=20,
            ),
        ),
    ]
