# Generated by Django 5.2.6 on 2025-09-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PestOrDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "scientific_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Pest", "Pest"), ("Disease", "Disease")],
                        max_length=20,
                    ),
                ),
                ("symptoms", models.TextField()),
                ("causes", models.TextField(blank=True, null=True)),
                ("identification_tips", models.TextField(blank=True, null=True)),
                ("prevention_methods", models.TextField(blank=True, null=True)),
                ("management_strategies", models.TextField(blank=True, null=True)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="pests_diseases/featured/"
                    ),
                ),
                (
                    "example_images",
                    models.ImageField(
                        blank=True, null=True, upload_to="pests_diseases/examples/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affected_crops",
                    models.ManyToManyField(
                        blank=True, related_name="affected_by", to="crops.crop"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pest or Disease",
                "verbose_name_plural": "Pests and Diseases",
                "ordering": ["name"],
            },
        ),
    ]
