# Generated by Django 5.2.7 on 2025-10-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="market",
            name="description_ky",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="market",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="market",
            name="name_en",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="market",
            name="name_ky",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="market",
            name="name_ru",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="category_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="category_ky",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="category_ru",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ky",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ky",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
