# Generated by Django 5.2.7 on 2025-11-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_market_description_en_market_description_ky_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketprice",
            name="notes_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketprice",
            name="notes_ky",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketprice",
            name="notes_ru",
            field=models.TextField(blank=True, null=True),
        ),
    ]
