# Generated by Django 5.2.7 on 2025-11-05 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatisticCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'Price of goods', 'Exports of goods')",
                        max_length=200,
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Category name (e.g., 'Price of goods', 'Exports of goods')",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        help_text="Category name (e.g., 'Price of goods', 'Exports of goods')",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "name_ky",
                    models.CharField(
                        help_text="Category name (e.g., 'Price of goods', 'Exports of goods')",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of this category"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of this category",
                        null=True,
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of this category",
                        null=True,
                    ),
                ),
                (
                    "description_ky",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of this category",
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order in which categories are displayed"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Statistic Category",
                "verbose_name_plural": "Statistic Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the statistic", max_length=300
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Title of the statistic", max_length=300, null=True
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        help_text="Title of the statistic", max_length=300, null=True
                    ),
                ),
                (
                    "title_ky",
                    models.CharField(
                        help_text="Title of the statistic", max_length=300, null=True
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description shown in the list",
                        max_length=500,
                    ),
                ),
                (
                    "short_description_en",
                    models.TextField(
                        blank=True,
                        help_text="Brief description shown in the list",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "short_description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Brief description shown in the list",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "short_description_ky",
                    models.TextField(
                        blank=True,
                        help_text="Brief description shown in the list",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "html_file_en",
                    models.FileField(
                        blank=True,
                        help_text="Complete HTML file with statistics content in English",
                        null=True,
                        upload_to="statistics/html/en/",
                    ),
                ),
                (
                    "html_file_ru",
                    models.FileField(
                        blank=True,
                        help_text="Complete HTML file with statistics content in Russian",
                        null=True,
                        upload_to="statistics/html/ru/",
                    ),
                ),
                (
                    "html_file_ky",
                    models.FileField(
                        blank=True,
                        help_text="Complete HTML file with statistics content in Kyrgyz",
                        null=True,
                        upload_to="statistics/html/ky/",
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Only published statistics are visible to users",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured statistics appear at the top"
                    ),
                ),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="agro_statistics.statisticcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistic",
                "verbose_name_plural": "Statistics",
                "ordering": ["-is_featured", "-publication_date", "-created_at"],
            },
        ),
    ]
