# Generated by Django 5.2.7 on 2025-11-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agro_statistics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statistic",
            name="category",
        ),
        migrations.DeleteModel(
            name="StatisticCategory",
        ),
    ]
