# Generated by Django 5.2.6 on 2025-10-01 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChemicalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("fertilizer", "Fertilizers"),
                            ("pesticide", "Pesticides"),
                            ("herbicide", "Herbicides"),
                            ("fungicide", "Fungicides"),
                            ("insecticide", "Insecticides"),
                            ("growth_regulator", "Growth Regulators"),
                            ("soil_conditioner", "Soil Conditioners"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Bootstrap icon class", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Chemical Categories",
                "ordering": ["category_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ChemicalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=100)),
                (
                    "active_ingredient",
                    models.CharField(
                        help_text="Main active chemical compounds", max_length=200
                    ),
                ),
                (
                    "concentration",
                    models.CharField(help_text="e.g., 20% EC, 80% WP", max_length=50),
                ),
                ("description", models.TextField()),
                (
                    "usage_instructions",
                    models.TextField(help_text="How to use this product"),
                ),
                (
                    "dosage",
                    models.CharField(
                        help_text="Recommended dosage per hectare or liter",
                        max_length=200,
                    ),
                ),
                (
                    "application_method",
                    models.CharField(
                        choices=[
                            ("foliar", "Foliar Application"),
                            ("soil", "Soil Application"),
                            ("seed", "Seed Treatment"),
                            ("drip", "Drip Irrigation"),
                            ("spray", "Spray Application"),
                        ],
                        max_length=20,
                    ),
                ),
                ("package_size", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "package_unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("liter", "Liter"),
                            ("gram", "Gram"),
                            ("ml", "Milliliter"),
                            ("bag", "Bag"),
                            ("bottle", "Bottle"),
                            ("packet", "Packet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "safety_warnings",
                    models.TextField(
                        blank=True, help_text="Safety precautions and warnings"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Government registration number",
                        max_length=100,
                    ),
                ),
                (
                    "target_crops",
                    models.TextField(help_text="Crops this product is suitable for"),
                ),
                (
                    "target_pests",
                    models.TextField(
                        blank=True, help_text="Pests/diseases this product treats"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="agro_supplies.chemicalcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "brand", "name"],
                "unique_together": {("name", "brand", "package_size", "package_unit")},
            },
        ),
        migrations.CreateModel(
            name="ChemicalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in local currency",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KGS",
                        help_text="Currency code (KGS, USD, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount percentage if any",
                        max_digits=5,
                    ),
                ),
                ("is_in_stock", models.BooleanField(default=True)),
                (
                    "stock_quantity",
                    models.IntegerField(
                        blank=True, help_text="Available quantity", null=True
                    ),
                ),
                (
                    "minimum_order",
                    models.IntegerField(default=1, help_text="Minimum order quantity"),
                ),
                (
                    "bulk_price_threshold",
                    models.IntegerField(
                        blank=True,
                        help_text="Minimum quantity for bulk pricing",
                        null=True,
                    ),
                ),
                (
                    "bulk_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price for bulk orders",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about pricing or availability",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who last updated this price",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="agro_supplies.chemicalproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "price"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("change_date", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True, help_text="Reason for price change", max_length=200
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chemical_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="agro_supplies.chemicalprice",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Price Histories",
                "ordering": ["-change_date"],
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "shop_type",
                    models.CharField(
                        choices=[
                            ("retail", "Retail Shop"),
                            ("wholesale", "Wholesale"),
                            ("distributor", "Distributor"),
                            ("online", "Online Store"),
                            ("cooperative", "Agricultural Cooperative"),
                        ],
                        default="retail",
                        max_length=20,
                    ),
                ),
                ("owner_name", models.CharField(blank=True, max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(help_text="Detailed address")),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("established_year", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "working_hours",
                    models.CharField(
                        blank=True, help_text="e.g., Mon-Fri: 8AM-6PM", max_length=200
                    ),
                ),
                ("delivery_available", models.BooleanField(default=False)),
                (
                    "delivery_radius_km",
                    models.IntegerField(
                        blank=True, help_text="Delivery radius in kilometers", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verified by administrators"
                    ),
                ),
                (
                    "chemical_products",
                    models.ManyToManyField(
                        related_name="available_shops",
                        through="agro_supplies.ChemicalPrice",
                        to="agro_supplies.chemicalproduct",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to="locations.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to="locations.country",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to="locations.region",
                    ),
                ),
            ],
            options={
                "ordering": ["country", "region", "city", "name"],
            },
        ),
        migrations.AddField(
            model_name="chemicalprice",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_prices",
                to="agro_supplies.shop",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chemicalprice",
            unique_together={("product", "shop")},
        ),
    ]
