# Generated by Django 5.2.7 on 2025-10-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agro_supplies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="google_maps_link",
            field=models.URLField(
                blank=True, help_text="Google Maps link to shop location"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="whatsapp_number",
            field=models.CharField(
                blank=True, help_text="WhatsApp contact number", max_length=20
            ),
        ),
    ]
