# Generated by Django 5.2.7 on 2025-11-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agro_supplies", "0002_add_shop_contact_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chemicalproduct",
            unique_together={("name", "brand", "package_size", "package_unit")},
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="description_ky",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="name_ky",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="name_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="safety_warnings_en",
            field=models.TextField(
                blank=True, help_text="Safety precautions and warnings", null=True
            ),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="safety_warnings_ky",
            field=models.TextField(
                blank=True, help_text="Safety precautions and warnings", null=True
            ),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="safety_warnings_ru",
            field=models.TextField(
                blank=True, help_text="Safety precautions and warnings", null=True
            ),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="target_crops_en",
            field=models.TextField(
                help_text="Crops this product is suitable for", null=True
            ),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="target_crops_ky",
            field=models.TextField(
                help_text="Crops this product is suitable for", null=True
            ),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="target_crops_ru",
            field=models.TextField(
                help_text="Crops this product is suitable for", null=True
            ),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="target_pests_en",
            field=models.TextField(
                blank=True, help_text="Pests/diseases this product treats", null=True
            ),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="target_pests_ky",
            field=models.TextField(
                blank=True, help_text="Pests/diseases this product treats", null=True
            ),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="target_pests_ru",
            field=models.TextField(
                blank=True, help_text="Pests/diseases this product treats", null=True
            ),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="usage_instructions_en",
            field=models.TextField(help_text="How to use this product", null=True),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="usage_instructions_ky",
            field=models.TextField(help_text="How to use this product", null=True),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="usage_instructions_ru",
            field=models.TextField(help_text="How to use this product", null=True),
        ),
        migrations.AlterUniqueTogether(
            name="chemicalproduct",
            unique_together={
                ("name", "brand", "package_size", "package_unit"),
                ("name_en", "brand", "package_size", "package_unit"),
                ("name_ky", "brand", "package_size", "package_unit"),
                ("name_ru", "brand", "package_size", "package_unit"),
            },
        ),
    ]
