# Generated by Django 5.2.7 on 2025-11-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agro_supplies", "0003_alter_chemicalproduct_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chemicalproduct",
            unique_together={
                ("name", "brand", "package_size", "package_unit"),
                ("name_en", "brand", "package_size", "package_unit"),
                ("name_ky", "brand", "package_size", "package_unit"),
                ("name_ru", "brand", "package_size", "package_unit"),
            },
        ),
        migrations.AddField(
            model_name="chemicalcategory",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chemicalcategory",
            name="description_ky",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chemicalcategory",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chemicalcategory",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chemicalcategory",
            name="name_ky",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chemicalcategory",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="active_ingredient_en",
            field=models.CharField(
                help_text="Main active chemical compounds", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="active_ingredient_ky",
            field=models.CharField(
                help_text="Main active chemical compounds", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="active_ingredient_ru",
            field=models.CharField(
                help_text="Main active chemical compounds", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="brand_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="brand_ky",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chemicalproduct",
            name="brand_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="description_ky",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="name_ky",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="name_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="chemicalproduct",
            unique_together={
                ("name", "brand", "package_size", "package_unit"),
                ("name", "brand_en", "package_size", "package_unit"),
                ("name", "brand_ky", "package_size", "package_unit"),
                ("name", "brand_ru", "package_size", "package_unit"),
                ("name_en", "brand", "package_size", "package_unit"),
                ("name_ky", "brand", "package_size", "package_unit"),
                ("name_ru", "brand", "package_size", "package_unit"),
            },
        ),
    ]
