# Generated by Django 5.2.6 on 2025-09-29 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("country", models.CharField(help_text="Country code", max_length=2)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("latitude", "longitude")},
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("temperature", models.FloatField(help_text="Temperature in Celsius")),
                (
                    "feels_like",
                    models.FloatField(help_text="Feels like temperature in Celsius"),
                ),
                (
                    "humidity",
                    models.PositiveIntegerField(help_text="Humidity percentage"),
                ),
                (
                    "pressure",
                    models.FloatField(help_text="Atmospheric pressure in hPa"),
                ),
                ("wind_speed", models.FloatField(help_text="Wind speed in m/s")),
                (
                    "wind_direction",
                    models.PositiveIntegerField(help_text="Wind direction in degrees"),
                ),
                (
                    "weather_main",
                    models.CharField(help_text="Main weather condition", max_length=50),
                ),
                (
                    "weather_description",
                    models.CharField(help_text="Weather description", max_length=100),
                ),
                (
                    "weather_icon",
                    models.CharField(help_text="Weather icon code", max_length=10),
                ),
                (
                    "visibility",
                    models.PositiveIntegerField(
                        blank=True, help_text="Visibility in meters", null=True
                    ),
                ),
                (
                    "uv_index",
                    models.FloatField(blank=True, help_text="UV index", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_data",
                        to="weather.weatherlocation",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "unique_together": {("location", "timestamp")},
            },
        ),
    ]
