# Generated by Django 5.2.7 on 2025-10-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['location', '-timestamp'], name='weather_wea_locatio_4dbed4_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['created_at'], name='weather_wea_created_eb097c_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='weather_wea_latitud_d971e8_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherlocation',
            index=models.Index(fields=['country', 'name'], name='weather_wea_country_3da444_idx'),
        ),
    ]
