# Generated by Django 5.2.6 on 2025-09-30 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO country code (e.g., KG, US, RU)",
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type_name",
                    models.CharField(
                        default="Region",
                        help_text="e.g., State, Oblast, Province",
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="locations.country",
                    ),
                ),
            ],
            options={
                "ordering": ["country__name", "name"],
                "unique_together": {("country", "name")},
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type_name",
                    models.CharField(
                        choices=[
                            ("city", "City"),
                            ("town", "Town"),
                            ("village", "Village"),
                            ("district", "District"),
                            ("settlement", "Settlement"),
                        ],
                        default="city",
                        max_length=20,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="locations.region",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
                "ordering": ["region__country__name", "region__name", "name"],
                "unique_together": {("region", "name")},
            },
        ),
    ]
