# Generated by Django 5.2.7 on 2025-10-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("region", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together={("country", "name")},
        ),
        migrations.AddField(
            model_name="city",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="name_ky",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="country",
            name="name_ky",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="country",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="region",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="name_ky",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={
                ("region", "name"),
                ("region", "name_en"),
                ("region", "name_ky"),
                ("region", "name_ru"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together={
                ("country", "name"),
                ("country", "name_en"),
                ("country", "name_ky"),
                ("country", "name_ru"),
            },
        ),
    ]
