# Generated by Django 5.2.6 on 2025-09-26 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SoilType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "texture",
                    models.CharField(
                        choices=[
                            ("Sandy", "Sandy"),
                            ("Loamy", "Loamy"),
                            ("Clay", "Clay"),
                            ("Silty", "Silty"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "drainage",
                    models.CharField(
                        choices=[
                            ("Good", "Good"),
                            ("Moderate", "Moderate"),
                            ("Poor", "Poor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nutrient_retention", models.CharField(max_length=100)),
                ("recommended_amendments", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "scientific_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("description", models.TextField()),
                (
                    "sunlight_needs",
                    models.CharField(
                        choices=[
                            ("Full Sun", "Full Sun"),
                            ("Partial Shade", "Partial Shade"),
                            ("Full Shade", "Full Shade"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "water_needs",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("climate_preference", models.CharField(max_length=200)),
                ("planting_seasons", models.TextField(blank=True, null=True)),
                (
                    "harvest_time",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nutrient_needs", models.TextField(blank=True, null=True)),
                ("recommended_usage", models.TextField(blank=True, null=True)),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="crops/images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "soil_preference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_crops",
                        to="crops.soiltype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
