# Generated by Django 5.2.7 on 2025-10-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crop",
            name="soil_preference",
        ),
        migrations.DeleteModel(
            name="SoilType",
        ),
    ]
