# Generated by Django 5.2.6 on 2025-09-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_comment_parent_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(),
        ),
    ]
