# Generated by Django 5.2.6 on 2025-09-29 08:38

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_alter_blogpost_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="featured_video",
            field=models.FileField(
                blank=True,
                help_text="Upload a video file (MP4, WebM, or OGG format, max 50MB)",
                null=True,
                upload_to=forum.models.get_post_video_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "webm", "ogg"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube video URL (alternative to uploaded video)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Main image for the post (recommended: 1200x630px)",
                null=True,
                upload_to="blog/featured/",
            ),
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Additional images for the post",
                        upload_to=forum.models.get_post_image_path,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, help_text="Optional image caption", max_length=200
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for accessibility",
                        max_length=200,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blog_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="forum.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
    ]
