# Generated by Django 5.2.6 on 2025-09-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_like"),
    ]

    operations = []
