# Generated by Django 5.2.7 on 2025-10-05 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_blogpost_content_en_blogpost_content_ky_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-publication_date', 'is_published'], name='forum_blogp_publica_851691_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='forum_blogp_slug_d95cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category', '-publication_date'], name='forum_blogp_categor_644010_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_featured', 'is_published'], name='forum_blogp_is_feat_187041_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['blog_post', 'is_approved', 'parent_comment'], name='forum_comme_blog_po_74c8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-publication_date'], name='forum_comme_author__e030fd_idx'),
        ),
    ]
