# Generated by Django 5.2.7 on 2025-10-07 11:00

import django.core.validators
import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0008_blogpost_forum_blogp_publica_851691_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="html_file",
            field=models.FileField(
                blank=True,
                help_text="Upload an HTML file for the blog post content (alternative to rich text editor)",
                null=True,
                upload_to=forum.models.get_post_html_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["html", "htm"]
                    )
                ],
            ),
        ),
    ]
