# Generated by Django 5.2.7 on 2025-10-07 11:15

import django.core.validators
import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0010_blogpost_html_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="html_file_en",
            field=models.FileField(
                blank=True,
                help_text="Upload an HTML file for the blog post content",
                null=True,
                upload_to=forum.models.get_post_html_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["html", "htm"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="html_file_ky",
            field=models.FileField(
                blank=True,
                help_text="Upload an HTML file for the blog post content",
                null=True,
                upload_to=forum.models.get_post_html_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["html", "htm"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="html_file_ru",
            field=models.FileField(
                blank=True,
                help_text="Upload an HTML file for the blog post content",
                null=True,
                upload_to=forum.models.get_post_html_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["html", "htm"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="html_file",
            field=models.FileField(
                blank=True,
                help_text="Upload an HTML file for the blog post content",
                null=True,
                upload_to=forum.models.get_post_html_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["html", "htm"]
                    )
                ],
            ),
        ),
    ]
