# Generated by Django 5.2.7 on 2025-10-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0011_add_html_file_translations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(
                blank=True, help_text="Rich text content", null=True
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content_en",
            field=models.TextField(
                blank=True, help_text="Rich text content", null=True
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content_ky",
            field=models.TextField(
                blank=True, help_text="Rich text content", null=True
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content_ru",
            field=models.TextField(
                blank=True, help_text="Rich text content", null=True
            ),
        ),
    ]
